title: "Shailesh Singh | Android Developer"
description: ""
show_downloads: false
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  # Disable Recent Posts Section
show_excerpts: false
collections:
  posts:
    output: false
