title: Shailesh Singh | Android Developer
description: Experienced Android Developer with 7.5+ years of expertise in mobile app development
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  # Disable Recent Posts Section
paginate: 0
show_excerpts: false
collections:
  posts:
    output: false
